[workspace]
authors = ["Mark Servilla <mark.servilla@gmail.com>"]
channels = ["conda-forge","main"]
name = "soh"
platforms = ["linux-64", "linux-aarch64"]
#platforms = ["linux-64"]
version = "2025.03.18"

[tasks]

[dependencies]
python = "3.11.*"
requests = ">=2.32.3,<3"
daiquiri = ">=3.0.0,<4"
paramiko = ">=3.5.1,<4"
pendulum = ">=3.0.0,<4"
psycopg2 = ">=2.9.9,<3"
asyncssh = ">=2.20.0,<3"
aiodns = ">=3.0.0,<4"
pytzdata = ">=2020.1,<2021"
urllib3 = ">=2.3.0,<3"
cchardet = ">=2.1.7,<3"
ldap3 = ">=2.9.1,<3"
sqlalchemy = "1.4.46.*"
cryptography = ">=44.0.2,<45"
click = ">=8.1.8,<9"
aiohttp = ">=3.11.14,<4"
pip = ">=25.0.1,<26"
