[project]
authors = [
  {name = "Mark Servilla", email = "mark.servilla@gmail.com"}
]
dependencies = [
  "requests>=2.32.3,<3",
  "daiquiri>=3.0.0,<4",
  "paramiko>=3.5.1,<4",
  "pendulum>=3.0.0,<4",
  "psycopg2>=2.9.9,<3",
  "asyncssh>=2.20.0,<3",
  "aiodns>=3.0.0,<4",
  "pytzdata>=2020.1,<2021",
  "urllib3>=2.3.0,<3",
  "cchardet>=2.1.7,<3",
  "ldap3>=2.9.1,<3",
  "sqlalchemy==1.4.46",
  "cryptography>=44.0.2,<45",
  "click>=8.1.8,<9",
  "aiohttp>=3.11.14,<4",
]
name = "soh"
requires-python = ">=3.11,<3.14"
version = "2025.03.18"
license = {file = "LICENSE"}
readme = "README.md"

[project.urls]
repository = "https://github.com/PASTAplus/soh"
